### ISSUE TITLE
Handle > 1000 results in get_search_url()

### ISSUE THREAD

**Issue by mwengren** [oceanhackweek/ohw19-project-co_locators#10]
The default for erddapy is to return a maximum of 1000 rows in a search result.  

Probably not likely to happen very often, but we need to add some code to erddap_query.py to handle cases where there are more results than the first thousand.  Probably a for or while loop would do the trick.

**Comment by garggaurangi** [comment]
@mwengren Hi!
I am a second year undergraduate and I am interested to contribute for ioos/colocate. I have some questions
1) How can I reproduce this issue?
2) What is the communication channel? 

Regards,
Gaurangi

**Comment by mwengren** [comment]
Hi @garggaurangi.  Please take a look at the issues labeled [GSoC](https://github.com/ioos/colocate/labels/GSoC) to see what we've selected for appropriate projects to work on during GSoC this year.  The projects are listed as 'GSoC Project 1' and 'GSoC Project 2' - combining a few issues together for each.  

This particular issue is lower priority and we hadn't included it in our list of projects.

**Comment by mwengren** [comment]
Closing this issue.  Will not fix/stale.
